project_id = "ejfimdkqrpfkfuovajpy"

[functions.bulk-add-tenants]
verify_jwt = false

[functions.generate-reports]
verify_jwt = false

[functions.generate-daily-forecast]
verify_jwt = false

[functions.pipeline-forecast]
verify_jwt = false

[functions.send-earnings-summary]
verify_jwt = false

